import Head from 'next/head'
import Image from 'next/image'
import Navbar from './components/Navbar';
import styled from "styled-components";



export default function Home() {
  return (
    <div >
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeDiv>
          <FirstView>
            <Navbar />
          </FirstView>
      </HomeDiv>
    </div>
  )
}

const HomeDiv = styled.div`
  
`;
const FirstView = styled.div`
  height: 100vh;
`;